name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: redhat-actions/s2i-build@v2
    - name: Build the Docker image
      run: make build
